
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author monster
 */
public class doktorArayuzu extends javax.swing.JFrame {

     
    
    public doktorArayuzu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_hastalar = new javax.swing.JButton();
        btn_ilacyaz = new javax.swing.JButton();
        btn_recete = new javax.swing.JButton();
        btn_ana = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();
        lbl_addok = new javax.swing.JLabel();
        tabbedp = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_hastalar = new javax.swing.JTable();
        lbl_gecme = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_ilacyaz = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_arama = new javax.swing.JTextField();
        lbl_kisi = new javax.swing.JLabel();
        btn_sec = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_recete = new javax.swing.JTable();
        btn_recyaz = new javax.swing.JButton();
        lbl_rec = new javax.swing.JLabel();
        btn_cikar = new javax.swing.JButton();
        btn_ekle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doktor Arayüzü");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 163, 163));

        btn_hastalar.setBackground(new java.awt.Color(0, 163, 163));
        btn_hastalar.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_hastalar.setForeground(new java.awt.Color(255, 255, 255));
        btn_hastalar.setText("Hastalar");
        btn_hastalar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_hastalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hastalarActionPerformed(evt);
            }
        });

        btn_ilacyaz.setBackground(new java.awt.Color(0, 160, 141));
        btn_ilacyaz.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_ilacyaz.setForeground(new java.awt.Color(255, 255, 255));
        btn_ilacyaz.setText("İlaç Yaz");
        btn_ilacyaz.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ilacyaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ilacyazActionPerformed(evt);
            }
        });

        btn_recete.setBackground(new java.awt.Color(0, 163, 163));
        btn_recete.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_recete.setForeground(new java.awt.Color(255, 255, 255));
        btn_recete.setText("Yazılan İlaçlar");
        btn_recete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_recete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receteActionPerformed(evt);
            }
        });

        btn_ana.setBackground(new java.awt.Color(0, 160, 141));
        btn_ana.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_ana.setForeground(new java.awt.Color(255, 255, 255));
        btn_ana.setText("Ana Sayfa");
        btn_ana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anaActionPerformed(evt);
            }
        });

        btn_cikis.setBackground(new java.awt.Color(0, 160, 141));
        btn_cikis.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_cikis.setForeground(new java.awt.Color(255, 255, 255));
        btn_cikis.setText("Çıkış");
        btn_cikis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        lbl_addok.setFont(new java.awt.Font("Segoe UI Black", 3, 20)); // NOI18N
        lbl_addok.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addok.setText("Merhaba ...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ilacyaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hastalar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_recete, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(btn_ana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_addok)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_addok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_ana, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_hastalar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ilacyaz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_recete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        tabbedp.setBackground(new java.awt.Color(0, 153, 153));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hasta Adı:");

        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        tab_hastalar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab_hastalar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ali Kaya", "1120560302", "BAĞKUR", "01/11/1987", "Bursa"},
                {"Seda Taş", "4562308956", "YOK", "31/08/2000", "Ankara"},
                {"Eylül Deniz", "1304568594", "YOK", "05/05/2005", "Sivas"},
                {"Barış Çelik", "1436583282", "SGK", "09/12/2010", "Diyarbakır"},
                {"Elif Çapa", "4879653212", "BAĞKUR", "21/03/2008", "İstanbul"},
                {"Ahmet Doğan", "1032586544", "SGK", "06/12/1987", "Bursa"},
                {"Ayşe Yaşar", "7803216548", "SGK", "30/09/1954", "Ankara"},
                {"Sedanur Suskun", "9852035478", "YOK", "07/07/2001", "Sivas"},
                {"Beyza Keskin", "1324201264", "SGK", "14/07/2005", "Diyarbakır"},
                {"Cemre Öztunç", "1341568716", "BAĞKUR", "07/06/2005", "Van"},
                {"Beyzanur Mengeş", "1462131564", "YOK", "29/06/2005", "Şanlıurfa"},
                {"Melek Sarı", "2301549518", "BAĞKUR", "29/02/1977", "Ankara"},
                {"Ömer Özgenç", "1602304568", "SGK", "08/12/2000", "İzmir"},
                {"Zinnet Arıcan", "1334568956", "YOK", "21/01/2003", "Rize"}
            },
            new String [] {
                "Ad-Soyad", "TC", "Sigorta", "Doğum Tarihi", "Şehir"
            }
        ));
        tab_hastalar.setRowHeight(25);
        tab_hastalar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_hastalarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_hastalar);

        lbl_gecme.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_gecme, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_gecme, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        tabbedp.addTab("Hastalar", jPanel3);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_ilacyaz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab_ilacyaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "8699676790326", "GLUCAGEN 1 MG HYPOKİT ENJ. FLAKON",  new Integer(12),  new Integer(50)},
                {"2", "8699809010215", "AMARYL 2 MG TB",  new Integer(80),  new Integer(62)},
                {"3", "8699676950706 ", "NOVOMİX FLEXPEN ",  new Integer(50),  new Integer(33)},
                {"4", "8699676770489", "AMARYL 3 MG TABLET",  new Integer(20),  new Integer(42)},
                {"5", "8699676770472", "INSULATARD HM 100 IU/ ML FLAKON ",  new Integer(16),  new Integer(70)},
                {"6", "8699676770496 ", "MİXTARD 30 HM 100 IU/ML FLAKON",  new Integer(13),  new Integer(90)},
                {"7", "8699543010144", "ACTRAPİD HM 100 I.U. FLAKON ",  new Integer(15),  new Integer(23)},
                {"8", "8699543090092 ", "GLİMAX 1 MG. TB.",  new Integer(8),  new Integer(45)},
                {"9", "8699676950799", "BETANORM TABLET ",  new Integer(5),  new Integer(68)},
                {"10", "8699809950634", "DİAFORMİN 1000 MG TABLET",  new Integer(14),  new Integer(19)},
                {"11", "8699809950665 ", "LEVEMİR FLEXPEN 100U/ML",  new Integer(18),  new Integer(55)},
                {"12", "8699673774213", "LANTUS SOLOSTAR 100U/ML",  new Integer(25),  new Integer(29)},
                {"13", "8699673954196 ", "APİDRA SOLOSTAR 100 U/ML 3 ML ",  new Integer(19),  new Integer(64)},
                {"14", "8699504090857", "GLUCOBAY 100 MG TAB ",  new Integer(30),  new Integer(30)}
            },
            new String [] {
                "İlaç ID", "Barkod", "Ürün Adı", "Kullanım Yaşı", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_ilacyaz.setRowHeight(25);
        tab_ilacyaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ilacyazMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_ilacyaz);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 807, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("İlaç Ara:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, 26));

        txt_arama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aramaActionPerformed(evt);
            }
        });
        txt_arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_aramaKeyReleased(evt);
            }
        });
        jPanel2.add(txt_arama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 163, 30));

        lbl_kisi.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel2.add(lbl_kisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 540, 30));

        btn_sec.setBackground(new java.awt.Color(0, 160, 141));
        btn_sec.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_sec.setForeground(new java.awt.Color(255, 255, 255));
        btn_sec.setText("SEÇ");
        btn_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 110, -1));

        tabbedp.addTab("İlaç Yaz", jPanel2);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        tab_recete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab_recete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İlaç ID", "Barkod", "Ürün Adı", "Kullanım Yaşı", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_recete.setRowHeight(25);
        jScrollPane3.setViewportView(tab_recete);

        btn_recyaz.setBackground(new java.awt.Color(0, 163, 163));
        btn_recyaz.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_recyaz.setForeground(new java.awt.Color(255, 255, 255));
        btn_recyaz.setText("Reçete Yazdır");
        btn_recyaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recyazActionPerformed(evt);
            }
        });

        lbl_rec.setBackground(new java.awt.Color(255, 255, 255));
        lbl_rec.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        btn_cikar.setBackground(new java.awt.Color(0, 160, 141));
        btn_cikar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_cikar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cikar.setText("Çıkar");
        btn_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikarActionPerformed(evt);
            }
        });

        btn_ekle.setBackground(new java.awt.Color(0, 160, 141));
        btn_ekle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_ekle.setForeground(new java.awt.Color(255, 255, 255));
        btn_ekle.setText("İlaç Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btn_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_recyaz, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_rec, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_recyaz)
                    .addComponent(lbl_rec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cikar)
                    .addComponent(btn_ekle))
                .addGap(39, 39, 39))
        );

        tabbedp.addTab("Yazılan İlaçlar", jPanel4);

        getContentPane().add(tabbedp, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, -40, -1, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_hastalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hastalarActionPerformed
        tabbedp.setSelectedIndex(0);
    }//GEN-LAST:event_btn_hastalarActionPerformed

    private void btn_ilacyazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ilacyazActionPerformed
        tabbedp.setSelectedIndex(1);
    }//GEN-LAST:event_btn_ilacyazActionPerformed

    private void btn_receteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receteActionPerformed
        tabbedp.setSelectedIndex(2);
    }//GEN-LAST:event_btn_receteActionPerformed

    private void btn_anaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anaActionPerformed
        giris ana=new giris();
       
        ana.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_anaActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
       DefaultTableModel model=(DefaultTableModel) tab_hastalar.getModel();
       TableRowSorter<DefaultTableModel> model1=new TableRowSorter<>(model);
       tab_hastalar.setRowSorter(model1);
       model1.setRowFilter(RowFilter.regexFilter(txt_search.getText()));
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_aramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_aramaKeyReleased
        DefaultTableModel obj=(DefaultTableModel) tab_ilacyaz.getModel();
        TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
        tab_ilacyaz.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txt_arama.getText()));
    }//GEN-LAST:event_txt_aramaKeyReleased

    private void tab_hastalarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_hastalarMouseClicked
        int secilenSatir=tab_hastalar.getSelectedRow();
        if (secilenSatir!=-1)
        {
            String adSoyad= (String) tab_hastalar.getValueAt(secilenSatir, 0);
            String TC=(String) tab_hastalar.getValueAt(secilenSatir, 1);
            
            String dogumYili=(String) tab_hastalar.getValueAt(secilenSatir, 3);
            lbl_gecme.setText("Hasta seçildi ilaç yazabilirsiniz.");
            
            DateTimeFormatter f=DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dogumYili1=LocalDate.parse(dogumYili,f);
            LocalDate simdikiZaman=LocalDate.now();
            Period yashesap=Period.between(dogumYili1,simdikiZaman );
            int yas=yashesap.getYears();
            
            lbl_kisi.setText(TC+" "+adSoyad+" "+yas+" yaşında.");
            
            tabbedp.setSelectedIndex(1);
          }
            
            //***********************dosyaya aktarma
            
            //***********adsoyad
            
            File dosya1=new File("ad.txt");
            try {
                dosya1.createNewFile();
                 FileWriter d = new FileWriter(dosya1);
                  if (secilenSatir!=-1) 
                  {
            String adSoyad= (String) tab_hastalar.getValueAt(secilenSatir, 0);
            d.write(adSoyad);
                  }
                 d.close();
            } catch (IOException ex) {
                System.out.println("hata");
            }
            
            
            ///****************tc
            File dosya2=new File("tc.txt");
            try {
                dosya2.createNewFile();
                FileWriter d = new FileWriter(dosya2);
                if (secilenSatir!=-1) 
                {
            String TC= (String) tab_hastalar.getValueAt(secilenSatir, 1);
            d.write(TC);
                  }
                 d.close();
            } catch (IOException ex) {
                System.out.println("hata");
            }
            
            //*********** sigorta
            
            File dosya3=new File("sigorta.txt");
            try {
                dosya3.createNewFile();
                 FileWriter d = new FileWriter(dosya3);
                  if (secilenSatir!=-1) 
                  {
            String sigorta= (String) tab_hastalar.getValueAt(secilenSatir, 2);
            d.write(sigorta);
                  }
                 d.close();
            } catch (IOException ex) {
                System.out.println("hata");
            }
            
            //**********dogum tarihi
            
            File dosya4=new File("dogum.txt");
            try {
                dosya4.createNewFile();
                 FileWriter d = new FileWriter(dosya4);
                  if (secilenSatir!=-1) 
                  {
            String sigorta= (String) tab_hastalar.getValueAt(secilenSatir, 3);
            d.write(sigorta);
                  }
                 d.close();
            } catch (IOException ex) {
                System.out.println("hata");
            }
       
    }//GEN-LAST:event_tab_hastalarMouseClicked

    private void tab_ilacyazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ilacyazMouseClicked
        int secilenSatir=tab_hastalar.getSelectedRow();
        String dogumYili=(String) tab_hastalar.getValueAt(secilenSatir, 3);
        
         DateTimeFormatter f=DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dogumYili1=LocalDate.parse(dogumYili,f);
            LocalDate simdikiZaman=LocalDate.now();
            Period yashesap=Period.between(dogumYili1,simdikiZaman );
            int yas=yashesap.getYears();
            
            int secilenSatir2=tab_ilacyaz.getSelectedRow();
                int sutunYas=(int) tab_ilacyaz.getValueAt(secilenSatir2, 3);
            // String sutunYasString = (String) tab_ilacyaz.getValueAt(secilenSatir, 3);   //object olsaydı bunu yapmak zorunda kalacaktık
            // int sutunYas = Integer.parseInt(sutunYasString);
        
            if (yas < sutunYas ) 
            {
                JOptionPane.showMessageDialog(null, "Hastaya yaşından dolayı bu ilaç verilemez.", "Hasta Yaşı", JOptionPane.ERROR_MESSAGE);
            }
       
    }//GEN-LAST:event_tab_ilacyazMouseClicked

    private void btn_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secActionPerformed
        TableModel sekil1=tab_ilacyaz.getModel();
        int[] indis=tab_ilacyaz.getSelectedRows();
        Object[] satir=new Object[5];
        DefaultTableModel sekil2=(DefaultTableModel) tab_recete.getModel();
        for (int i = 0; i < indis.length; i++) {
            satir[0]=sekil1.getValueAt(indis[i], 0);
            satir[1]=sekil1.getValueAt(indis[i], 1);
            satir[2]=sekil1.getValueAt(indis[i], 2);
            satir[3]=sekil1.getValueAt(indis[i], 3);
            satir[4]=sekil1.getValueAt(indis[i], 4);
            
            sekil2.addRow(satir);
            
            tabbedp.setSelectedIndex(2);
        }
    }//GEN-LAST:event_btn_secActionPerformed

    private void btn_recyazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recyazActionPerformed
            int receteNo=(int) (Math.random()*100)+1;
        File file=new File("dosyam.txt");
        
            try {
                file.createNewFile();
                 FileWriter f = new FileWriter(file,true);
                 
                 int secilenSatir=tab_recete.getSelectedRow();
                 if (secilenSatir==-1) 
                 {
                    JOptionPane.showMessageDialog(null, "Lütfen bir satır seçin.", "Hata", JOptionPane.ERROR_MESSAGE);
                }
                
                 for (int i = 0; i < tab_recete.getColumnCount(); i++) {
               f.write(tab_recete.getValueAt(secilenSatir, i).toString());
                       if (i<tab_recete.getColumnCount()-1)
                       {
                          f.write("  ");
                      }
                  }
                  f.write("  "); 
                   f.write(Integer.toString( +receteNo)+"\n");
                   lbl_rec.setText("Reçete yazıldı.");
                  JOptionPane.showMessageDialog(null, "Reçete No:"+receteNo);
                  
                  f.close();
            } catch (IOException ex) {
                System.out.println("hata");
            }
        
        
    }//GEN-LAST:event_btn_recyazActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void btn_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikarActionPerformed
        DefaultTableModel model=(DefaultTableModel) tab_recete.getModel();
        if (tab_recete.getSelectedRowCount()==1)
        {
             model.removeRow(tab_recete.getSelectedRow());
        }
    }//GEN-LAST:event_btn_cikarActionPerformed

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        tabbedp.setSelectedIndex(1);
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void txt_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aramaActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktorArayuzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktorArayuzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktorArayuzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktorArayuzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktorArayuzu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ana;
    private javax.swing.JButton btn_cikar;
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_hastalar;
    private javax.swing.JButton btn_ilacyaz;
    private javax.swing.JButton btn_recete;
    private javax.swing.JButton btn_recyaz;
    private javax.swing.JButton btn_sec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_addok;
    private javax.swing.JLabel lbl_gecme;
    private javax.swing.JLabel lbl_kisi;
    private javax.swing.JLabel lbl_rec;
    private javax.swing.JTable tab_hastalar;
    private javax.swing.JTable tab_ilacyaz;
    private javax.swing.JTable tab_recete;
    private javax.swing.JTabbedPane tabbedp;
    private javax.swing.JTextField txt_arama;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
