
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author monster
 */
public class doktorGirisi extends javax.swing.JFrame {

    /**
     * Creates new form doktorGirisi
     */
    public doktorGirisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_tel = new javax.swing.JLabel();
        cmb_ulkeler = new javax.swing.JComboBox<>();
        txt_tel = new javax.swing.JTextField();
        lbl_ad = new javax.swing.JLabel();
        txt_ad = new javax.swing.JTextField();
        btn_DokGiris = new javax.swing.JButton();
        lbl_TC = new javax.swing.JLabel();
        txt_tc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doktor Girişi\n");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hoşgeldinizz.. ");

        lbl_tel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tel.setText("Telefon Numarası:");

        cmb_ulkeler.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_ulkeler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ", "TÜRKİYE", "ALMANYA", "İNGİLTERE", "YUNANİSTAN", "KIBRIS", "AZERBAYCAN", "RUSYA", "ÇİN" }));
        cmb_ulkeler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ulkelerActionPerformed(evt);
            }
        });

        txt_tel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_ad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_ad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ad.setText("Ad - Soyad:");

        txt_ad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_DokGiris.setBackground(new java.awt.Color(102, 102, 102));
        btn_DokGiris.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_DokGiris.setForeground(new java.awt.Color(255, 255, 255));
        btn_DokGiris.setText("Giriş Yap");
        btn_DokGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DokGirisActionPerformed(evt);
            }
        });

        lbl_TC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TC.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TC.setText("T.C :");

        txt_tc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ad)
                            .addComponent(txt_tc, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_ulkeler, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_DokGiris))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ad)
                    .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TC)
                    .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ulkeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tel))
                .addGap(40, 40, 40)
                .addComponent(btn_DokGiris)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\monster\\OneDrive\\Resimler\\Ekran Görüntüleri\\dokkk.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_ulkelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ulkelerActionPerformed
        if (cmb_ulkeler.getSelectedIndex()==0) {
           
        }
        if (cmb_ulkeler.getSelectedIndex()==1) {
            txt_tel.setText("+90");
        }
        if (cmb_ulkeler.getSelectedIndex()==2) {
            txt_tel.setText("+49");
        }
        if (cmb_ulkeler.getSelectedIndex()==3) {
            txt_tel.setText("+44");
        }
        if (cmb_ulkeler.getSelectedIndex()==4) {
            txt_tel.setText("+30");
        }
        if (cmb_ulkeler.getSelectedIndex()==5) {
            txt_tel.setText("+357");
        }
        if (cmb_ulkeler.getSelectedIndex()==6) {
            txt_tel.setText("+994");
        }
        if (cmb_ulkeler.getSelectedIndex()==7) {
            txt_tel.setText("+7");
        }
        if (cmb_ulkeler.getSelectedIndex()==8) {
            txt_tel.setText("+86");
        }
        
    }//GEN-LAST:event_cmb_ulkelerActionPerformed

    private void btn_DokGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DokGirisActionPerformed
           String ad=txt_ad.getText();
           String tck=txt_tc.getText();
           String tel=txt_tel.getText();
          
           if (ad.equals("esra")&& tck.equals("12345")&& tel.equals("+901234567")&& cmb_ulkeler.getSelectedIndex()==1) {
            doktorArayuzu doktor=new doktorArayuzu();
            doktor.setVisible(true);
               setVisible(false);
        }
           else{
             JOptionPane.showMessageDialog(null, "Kullanıcı adı , TC kimlik numarasi veya telefon numarasi hatali.", "uyari", JOptionPane.ERROR_MESSAGE);
           }
           
    }//GEN-LAST:event_btn_DokGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktorGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktorGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktorGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktorGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktorGirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DokGiris;
    private javax.swing.JComboBox<String> cmb_ulkeler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_TC;
    private javax.swing.JLabel lbl_ad;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_tc;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
