
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author monster
 */
public class eczaneGirisi extends javax.swing.JFrame {

    /**
     * Creates new form eczaneGirisi
     */
    public eczaneGirisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_EczAd = new javax.swing.JLabel();
        lbl_EczTC = new javax.swing.JLabel();
        lbl_Etel = new javax.swing.JLabel();
        txt_ad = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_tc = new javax.swing.JTextField();
        cmb_ulke = new javax.swing.JComboBox<>();
        btn_EczGiris = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hoşgeldiniz..");

        lbl_EczAd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_EczAd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_EczAd.setText("Ad - Soyad:");

        lbl_EczTC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_EczTC.setForeground(new java.awt.Color(255, 255, 255));
        lbl_EczTC.setText("T.C :");

        lbl_Etel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Etel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Etel.setText("Telefon Numarası :");

        txt_ad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_tel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_tc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmb_ulke.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_ulke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ", "TÜRKİYE", "ALMANYA", "İNGİLTERE", "YUNANİSTAN", "KIBRIS", "AZERBAYCAN", "RUSYA", "ÇİN" }));
        cmb_ulke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ulkeActionPerformed(evt);
            }
        });

        btn_EczGiris.setBackground(new java.awt.Color(102, 102, 102));
        btn_EczGiris.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_EczGiris.setForeground(new java.awt.Color(255, 255, 255));
        btn_EczGiris.setText("Giriş Yap");
        btn_EczGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EczGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_EczAd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_EczTC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Etel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_EczGiris)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_tel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(txt_tc)
                                    .addComponent(txt_ad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_ulke, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_EczAd)
                    .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_EczTC)
                    .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Etel)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btn_EczGiris)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\monster\\OneDrive\\Resimler\\Ekran Görüntüleri\\ec.png")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_ulkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ulkeActionPerformed
        if (cmb_ulke.getSelectedIndex()==0) {
            //İNDİS SIFIRDAN BASLIYOR- SECİNİZ
        }
        if (cmb_ulke.getSelectedIndex()==1) {
            txt_tel.setText("+90");
        }
        if (cmb_ulke.getSelectedIndex()==2) {
            txt_tel.setText("+49");
        }
        if (cmb_ulke.getSelectedIndex()==3) {
            txt_tel.setText("+44");
        }
        if (cmb_ulke.getSelectedIndex()==4) {
            txt_tel.setText("+30");
        }
        if (cmb_ulke.getSelectedIndex()==5) {
            txt_tel.setText("+357");
        }
        if (cmb_ulke.getSelectedIndex()==6) {
            txt_tel.setText("+994");
        }
        if (cmb_ulke.getSelectedIndex()==7) {
            txt_tel.setText("+7");
        }
        if (cmb_ulke.getSelectedIndex()==8) {
            txt_tel.setText("+86");
        }
        
    }//GEN-LAST:event_cmb_ulkeActionPerformed

    private void btn_EczGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EczGirisActionPerformed
            String ad=txt_ad.getText();
           String tck=txt_tc.getText();
           String tel=txt_tel.getText();
          
           if (ad.equals("esra")&& tck.equals("12345")&& tel.equals("+901234567")&& cmb_ulke.getSelectedIndex()==1) {
            eczaneArayuzu eczane=new eczaneArayuzu();
            eczane.setVisible(true);
               setVisible(false);
        }
           else{
             JOptionPane.showMessageDialog(null, "Kullanıcı adı , TC kimlik numarasi veya telefon numarasi hatali.", "uyari", JOptionPane.ERROR_MESSAGE);
           }
        
    }//GEN-LAST:event_btn_EczGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eczaneGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eczaneGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eczaneGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eczaneGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eczaneGirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EczGiris;
    private javax.swing.JComboBox<String> cmb_ulke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_EczAd;
    private javax.swing.JLabel lbl_EczTC;
    private javax.swing.JLabel lbl_Etel;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_tc;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
