
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author monster
 */
public class eczaneArayuzu extends javax.swing.JFrame {

    /**
     * Creates new form eczaneArayuzu
     */
    public eczaneArayuzu() {
        initComponents();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panel_menu = new javax.swing.JPanel();
        btn_ana = new javax.swing.JButton();
        btn_recete = new javax.swing.JButton();
        btn_sepet = new javax.swing.JButton();
        btn_ilac = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_cikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tab_panel = new javax.swing.JTabbedPane();
        panel_rec = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_recetecz = new javax.swing.JTable();
        btn_ara = new javax.swing.JButton();
        txt_no = new javax.swing.JTextField();
        lbl_adsoyad = new javax.swing.JLabel();
        lbl_sigorta = new javax.swing.JLabel();
        lbl_tc = new javax.swing.JLabel();
        txt_ads = new javax.swing.JTextField();
        txt_tc = new javax.swing.JTextField();
        txt_dogum = new javax.swing.JTextField();
        lbl_dogum = new javax.swing.JLabel();
        txt_sigorta = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        lbl_toplam = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lbl_sigortaturu = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btn_satis = new javax.swing.JButton();
        lbl_indirim = new javax.swing.JLabel();
        lbl_odenecek = new javax.swing.JLabel();
        panel_ilac = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_ilac = new javax.swing.JTable();
        btn_sec = new javax.swing.JButton();
        panel_sepet = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_sepet = new javax.swing.JTable();
        btn_cikar = new javax.swing.JButton();
        txt_hesap = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eczane Arayüzü");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(0, 102, 102));

        btn_ana.setBackground(new java.awt.Color(0, 102, 102));
        btn_ana.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_ana.setForeground(new java.awt.Color(255, 255, 255));
        btn_ana.setText("Ana Sayfa");
        btn_ana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anaActionPerformed(evt);
            }
        });

        btn_recete.setBackground(new java.awt.Color(0, 102, 102));
        btn_recete.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_recete.setForeground(new java.awt.Color(255, 255, 255));
        btn_recete.setText("E-Reçete Sorgula");
        btn_recete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_recete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receteActionPerformed(evt);
            }
        });

        btn_sepet.setBackground(new java.awt.Color(0, 102, 102));
        btn_sepet.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_sepet.setForeground(new java.awt.Color(255, 255, 255));
        btn_sepet.setText("Sepet");
        btn_sepet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_sepet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sepetActionPerformed(evt);
            }
        });

        btn_ilac.setBackground(new java.awt.Color(0, 102, 102));
        btn_ilac.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_ilac.setForeground(new java.awt.Color(255, 255, 255));
        btn_ilac.setText("İlaçlar");
        btn_ilac.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ilac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ilacActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rage Italic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eczanesi");

        jLabel3.setFont(new java.awt.Font("Rage Italic", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manolya");

        btn_cikis.setBackground(new java.awt.Color(0, 102, 102));
        btn_cikis.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btn_cikis.setForeground(new java.awt.Color(255, 255, 255));
        btn_cikis.setText("Çıkış");
        btn_cikis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_recete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_ilac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sepet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cikis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ana, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_recete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ilac, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sepet, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 142, Short.MAX_VALUE))
        );

        getContentPane().add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 132, 224, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\monster\\OneDrive\\Resimler\\Ekran Görüntüleri\\mo.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 224, -1));

        tab_panel.setBackground(new java.awt.Color(255, 204, 204));
        tab_panel.setForeground(new java.awt.Color(0, 102, 102));

        panel_rec.setBackground(new java.awt.Color(0, 153, 153));
        panel_rec.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 204, 204));

        tab_recetecz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab_recetecz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İlaç ID", "Barkod", "Ürün Adı", "Kullanım Yaşı", "Fiyat", "Reçete No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_recetecz.setRowHeight(25);
        tab_recetecz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_receteczMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_recetecz);

        btn_ara.setBackground(new java.awt.Color(255, 153, 153));
        btn_ara.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_ara.setForeground(new java.awt.Color(255, 255, 255));
        btn_ara.setText("Ara");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        txt_no.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_no.setForeground(new java.awt.Color(102, 102, 102));
        txt_no.setText("Reçete No");
        txt_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_noKeyReleased(evt);
            }
        });

        lbl_adsoyad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_adsoyad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adsoyad.setText("Ad-Soyad :");

        lbl_sigorta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_sigorta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sigorta.setText("Sigorta :");

        lbl_tc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tc.setText("TC :");

        txt_ads.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_ads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adsActionPerformed(evt);
            }
        });

        txt_tc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txt_dogum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lbl_dogum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_dogum.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dogum.setText("Doğum Tarihi :");

        txt_sigorta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Hasta Bilgileri ");

        lbl_toplam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_toplam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_toplam.setText(".");

        jTextField2.setBackground(new java.awt.Color(255, 204, 204));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Satış Bilgileri");

        lbl_sigortaturu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_sigortaturu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sigortaturu.setText(".");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Nakit");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Kart");

        btn_satis.setBackground(new java.awt.Color(255, 153, 153));
        btn_satis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_satis.setForeground(new java.awt.Color(255, 255, 255));
        btn_satis.setText("Satışı Yap");
        btn_satis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_satisActionPerformed(evt);
            }
        });

        lbl_indirim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_indirim.setForeground(new java.awt.Color(255, 255, 255));
        lbl_indirim.setText(".");

        lbl_odenecek.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_odenecek.setForeground(new java.awt.Color(255, 255, 255));
        lbl_odenecek.setText(".");

        javax.swing.GroupLayout panel_recLayout = new javax.swing.GroupLayout(panel_rec);
        panel_rec.setLayout(panel_recLayout);
        panel_recLayout.setHorizontalGroup(
            panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_recLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_recLayout.createSequentialGroup()
                        .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_recLayout.createSequentialGroup()
                                .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_recLayout.createSequentialGroup()
                                        .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_recLayout.createSequentialGroup()
                                        .addComponent(lbl_dogum, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_dogum, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ads, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sigorta, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(58, 58, 58)
                        .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_satis)
                                .addComponent(lbl_sigortaturu, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                                .addComponent(lbl_toplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_recLayout.createSequentialGroup()
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_indirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_odenecek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_recLayout.createSequentialGroup()
                        .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_sigorta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel_recLayout.setVerticalGroup(
            panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_recLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ara)
                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_recLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbl_toplam)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_sigortaturu))
                    .addGroup(panel_recLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_adsoyad)
                            .addComponent(txt_ads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_recLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_indirim)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_odenecek)
                        .addGap(18, 18, 18)
                        .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(16, 16, 16)
                        .addComponent(btn_satis))
                    .addGroup(panel_recLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tc)
                            .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dogum)
                            .addComponent(txt_dogum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(panel_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sigorta)
                            .addComponent(txt_sigorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        tab_panel.addTab("E-Reçete Sorgula", panel_rec);

        panel_ilac.setBackground(new java.awt.Color(0, 153, 153));

        tab_ilac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab_ilac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "8699517010309", "AZOSİLİN 30 TB ",  new Integer(90)},
                {"2", "8699532287205", "DUOCİD ORAL SÜSPANSİYON 250MG/5ML 100ML",  new Integer(54)},
                {"3", "8699508270354", "DEPOSİLİN 1.2 IU FLK",  new Integer(63)},
                {"4", "8699508090075", "NİDAZOL 500 MG FİLM TABLET",  new Integer(72)},
                {"5", "8699502280205 ", "SUPRAX SUSPANSIYON 50 ML",  new Integer(80)},
                {"6", "8699502091757 ", "SUPRAX 400 MG ",  new Integer(20)},
                {"7", "8699508610020", "GENTA GOZ KULAK DAM ",  new Integer(24)},
                {"8", "8699508090501", "ROXİN 750 MG 14 TABLET",  new Integer(55)},
                {"9", "8699546090372 ", "AVELOX 400 MG 7 TABLET",  new Integer(67)},
                {"10", "8699505011059 ", "BACTRİM 400 / 80 MG 30 TABLET",  new Integer(73)},
                {"11", "8699522282241", "ZİNNAT 125MG/5ML",  new Integer(18)},
                {"12", "8699572790093", "TAZOCİN EF 4.5 FLK",  new Integer(45)},
                {"13", "8699517090219 ", "CRAVİT 500MG 7FİLM TB",  new Integer(40)},
                {"14", "8699532699688", "ZYVOXID 2 MG/ML ENFÜZYON",  new Integer(60)},
                {"15", "8699536090726", "PİTOKSİL400 MG TABLET",  new Integer(110)},
                {"16", "8699508090525", "SULCİD 750 MG 10 TB",  new Integer(23)},
                {"17", "8699505011356", "BACTRIM FORTE 20 TB ",  new Integer(48)},
                {"18", "8699502700758", "PENOS 400 MG. SURUP",  new Integer(95)},
                {"19", "8699525092779", "CEFAKS 500 MG TABLET",  new Integer(64)},
                {"20", "8699508700028", "KEMOPRIM 100 CC SUSP.",  new Integer(18)}
            },
            new String [] {
                "İlaç ID", "Barkod", "Ürün Adı", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_ilac.setRowHeight(25);
        tab_ilac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ilacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_ilac);

        btn_sec.setBackground(new java.awt.Color(255, 153, 153));
        btn_sec.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_sec.setForeground(new java.awt.Color(255, 255, 255));
        btn_sec.setText("Seç");
        btn_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ilacLayout = new javax.swing.GroupLayout(panel_ilac);
        panel_ilac.setLayout(panel_ilacLayout);
        panel_ilacLayout.setHorizontalGroup(
            panel_ilacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ilacLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_ilacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sec, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel_ilacLayout.setVerticalGroup(
            panel_ilacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ilacLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_sec)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        tab_panel.addTab("İlaçlar", panel_ilac);

        panel_sepet.setBackground(new java.awt.Color(0, 153, 153));

        tab_sepet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab_sepet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İlaç ID", "Barkod", "Ürün Adı", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_sepet.setRowHeight(25);
        tab_sepet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_sepetMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tab_sepet);

        btn_cikar.setBackground(new java.awt.Color(255, 153, 153));
        btn_cikar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cikar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cikar.setText("Çıkar");
        btn_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikarActionPerformed(evt);
            }
        });

        txt_hesap.setBackground(new java.awt.Color(255, 204, 204));
        txt_hesap.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_hesap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hesapActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Satışı Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_sepetLayout = new javax.swing.GroupLayout(panel_sepet);
        panel_sepet.setLayout(panel_sepetLayout);
        panel_sepetLayout.setHorizontalGroup(
            panel_sepetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sepetLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panel_sepetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(panel_sepetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_cikar)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                        .addComponent(txt_hesap, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panel_sepetLayout.setVerticalGroup(
            panel_sepetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sepetLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_cikar)
                .addGap(29, 29, 29)
                .addComponent(txt_hesap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        tab_panel.addTab("Sepet", panel_sepet);

        getContentPane().add(tab_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -35, -1, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sepetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sepetActionPerformed
        tab_panel.setSelectedIndex(2);
    }//GEN-LAST:event_btn_sepetActionPerformed

    private void btn_receteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receteActionPerformed
        tab_panel.setSelectedIndex(0);
    }//GEN-LAST:event_btn_receteActionPerformed

    private void btn_anaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anaActionPerformed
        giris ana=new giris();
        ana.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_anaActionPerformed

    private void btn_ilacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ilacActionPerformed
        tab_panel.setSelectedIndex(1);
    }//GEN-LAST:event_btn_ilacActionPerformed

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
         File file=new File("dosyam.txt");
        
        try {
            FileReader f=new FileReader(file);
            BufferedReader br=new BufferedReader(f);
            DefaultTableModel model=(DefaultTableModel) tab_recetecz.getModel();
            Object[]line=br.lines().toArray();
            for (int i = 0; i < line.length; i++) 
            {
                String [] satir=line[i].toString().split("  ");
                model.addRow(satir);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("hata");
        }
        
        //***************** ad
        
        File file1=new File("ad.txt");
        try {
            String yazi=Files.readString(file1.toPath());
            txt_ads.setText(yazi);
        } catch (IOException ex) {
            System.out.println("hata");
        }
        
        
        //************tc
         File file2=new File("tc.txt");
        try {
            String yazi=Files.readString(file2.toPath());
            txt_tc.setText(yazi);
        } catch (IOException ex) {
            System.out.println("hata");
        }
        
        
        //****sigorta
         File file3=new File("sigorta.txt");
        try {
            String yazi=Files.readString(file3.toPath());
            txt_sigorta.setText(yazi);
        } catch (IOException ex) {
            System.out.println("hata");
        }
        
        
        //*********dogumtarihi
         File file4=new File("dogum.txt");
        try {
            String yazi=Files.readString(file4.toPath());
            txt_dogum.setText(yazi);
        } catch (IOException ex) {
            System.out.println("hata");
        }
        
    }//GEN-LAST:event_btn_araActionPerformed

    private void tab_ilacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ilacMouseClicked
     
    }//GEN-LAST:event_tab_ilacMouseClicked

    private void btn_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secActionPerformed
         TableModel sekil1=tab_ilac.getModel();
        int[] indis=tab_ilac.getSelectedRows();
        Object[] satir=new Object[5];
        DefaultTableModel sekil2=(DefaultTableModel) tab_sepet.getModel();
        for (int i = 0; i < indis.length; i++) {
            satir[0]=sekil1.getValueAt(indis[i], 0);
            satir[1]=sekil1.getValueAt(indis[i], 1);
            satir[2]=sekil1.getValueAt(indis[i], 2);
            satir[3]=sekil1.getValueAt(indis[i], 3);
            
            sekil2.addRow(satir);
            
    }//GEN-LAST:event_btn_secActionPerformed
    }
    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void txt_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_noKeyReleased
        DefaultTableModel obj=(DefaultTableModel) tab_recetecz.getModel();
        TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
        tab_recetecz.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txt_no.getText()));
    }//GEN-LAST:event_txt_noKeyReleased

    private void txt_adsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adsActionPerformed

    private void tab_receteczMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_receteczMouseClicked
        int secilenSatir=tab_recetecz.getSelectedRow();
        if (secilenSatir!=-1) {
            String fiyat=(String) tab_recetecz.getValueAt(secilenSatir, 4);
            lbl_toplam.setText("Fiyat:  "+fiyat);
            
           lbl_sigortaturu.setText("Sigorta Türü:  "+txt_sigorta.getText());
           
        int indirim=0;
        int fiyatd=Integer.parseInt(fiyat);
            if (lbl_sigortaturu.getText().equals("Sigorta Türü:  SGK"))
            {
                 indirim=(int) ((int)fiyatd*0.2);
                lbl_indirim.setText("İndirim Miktarı:  "+indirim);
                lbl_odenecek.setText("Ödenecek Tutar"+Integer.toString(fiyatd-indirim));
            }
            
            else if (lbl_sigortaturu.getText().equals("Sigorta Türü:  BAĞKUR")) 
            {
                  indirim=(int) ((int)fiyatd*0.1);
                lbl_indirim.setText("İndirim Miktarı:  "+indirim);
                lbl_odenecek.setText("Ödenecek Tutar: "+Integer.toString(fiyatd-indirim));
            }
            
            else
            {
               lbl_indirim.setText("İndirim Miktarı:  0"); 
               lbl_odenecek.setText("Ödenecek Tutar:  "+Integer.toString(fiyatd-indirim));
            }
        }
    }//GEN-LAST:event_tab_receteczMouseClicked

    private void btn_satisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_satisActionPerformed
        JOptionPane.showMessageDialog(null, "Satış Başarılı Bir Şekilde Gerçekleşti", "SATIŞ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_satisActionPerformed

    private void btn_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikarActionPerformed
         DefaultTableModel model=(DefaultTableModel) tab_sepet.getModel();
        if (tab_sepet.getSelectedRowCount()==1) 
        {
             model.removeRow(tab_sepet.getSelectedRow());
        }
    }//GEN-LAST:event_btn_cikarActionPerformed

    private void txt_hesapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hesapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hesapActionPerformed

    private void tab_sepetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_sepetMouseClicked
       
        int satir=tab_sepet.getRowCount();
        int hesap=0;
        
        for (int i = 0; i < satir; i++) {
            int ilac=(int)tab_sepet.getValueAt(i, 3);
            hesap+=ilac;
        }
        txt_hesap.setText("Toplam Fiyat:  "+Integer.toString(hesap));
    }//GEN-LAST:event_tab_sepetMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Satış Başarılı Bir Şekilde Gerçekleşti", "SATIŞ", JOptionPane.INFORMATION_MESSAGE);
        setVisible(false);
        cikis cik=new cikis();
        cik.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eczaneArayuzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eczaneArayuzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eczaneArayuzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eczaneArayuzu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eczaneArayuzu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ana;
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_cikar;
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_ilac;
    private javax.swing.JButton btn_recete;
    private javax.swing.JButton btn_satis;
    private javax.swing.JButton btn_sec;
    private javax.swing.JButton btn_sepet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_adsoyad;
    private javax.swing.JLabel lbl_dogum;
    private javax.swing.JLabel lbl_indirim;
    private javax.swing.JLabel lbl_odenecek;
    private javax.swing.JLabel lbl_sigorta;
    private javax.swing.JLabel lbl_sigortaturu;
    private javax.swing.JLabel lbl_tc;
    private javax.swing.JLabel lbl_toplam;
    private javax.swing.JPanel panel_ilac;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_rec;
    private javax.swing.JPanel panel_sepet;
    private javax.swing.JTable tab_ilac;
    private javax.swing.JTabbedPane tab_panel;
    public javax.swing.JTable tab_recetecz;
    private javax.swing.JTable tab_sepet;
    private javax.swing.JTextField txt_ads;
    private javax.swing.JTextField txt_dogum;
    private javax.swing.JTextField txt_hesap;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_sigorta;
    private javax.swing.JTextField txt_tc;
    // End of variables declaration//GEN-END:variables

   
    }

